### ISSUE TITLE
Error in getter for watcher "currentPage"

### ISSUE THREAD

**Issue by sorxrob** [TahaSh/vue-paginate#48] opened 2017-03-10 00:07 UTC
Good day!

I followed everything in the docs and I get this error:

`Error in getter for watcher "currentPage"`

Am I missing something here?

**Comment by TahaSh** [comment] 2017-05-18 15:30
@sorxrob Can you please include the steps to reproduce this issue? Or it would be better if you give me a jsfiddle that has this issue.

**Comment by scottcarlson** [comment] 2017-06-01 18:47
@TahaSh This is happening to me as well. I can't reproduce the issue within jsFiddle. It's possible it's a scope issue arising from WebPack build.

My full error is:

`Error in getter for watcher "currentPage": "TypeError: Cannot read property 'foo' of undefined"`

I believe the error is thrown [here](https://github.com/TahaSh/vue-paginate/blob/master/src/components/Paginate.js#L32)

Where `this.$parent` has an undefined `paginate` property, but the `paginate` array is defined on my Vue instance data property.

**Comment by scottcarlson** [comment] 2017-06-05 23:29
Turn out this was happening because our application was wrapped in a slotted App.vue component. It seems the pagination component does not work within a slotted output.

Our solution was to use proper Vue component extension using the "[extends](https://vuejs.org/v2/api/#extends)" property so our application wouldn't be output within a \<slot\>.

**Comment by TahaSh** [comment] 2018-03-31 15:59
This issue should be fixed using the new `container` prop introduced in version `3.6.0`. [Check the docs to see how it's used.](https://github.com/TahaSh/vue-paginate#using-it-inside-a-components-slot)

**Closed** 2018-03-31 15:59 UTC
