### ISSUE TITLE
Returns to page 1 every ~10 seconds

### ISSUE THREAD

**Issue by khaledalam** [TahaSh/vue-paginate#81] opened 2018-03-28 18:50 UTC
When items are fetched every 10 seconds, it returns to page 1 automatically every time if i'm for example at page 3, how to prevent this action and after fetch stay at the current page instead!

`<paginate
                                    name="--"
                                    :list="--"
                                    :per="10"
                            >`

`...`

`<paginate-links
                                for="--"
                                tag="t-body"
                                :show-step-links="true"
                                :hide-single-page="true"></paginate-links>`

**Comment by charlesnjihia** [comment] 2018-03-28 19:29
what realease version are you using?

**Comment by khaledalam** [comment] 2018-03-28 19:30
@charlesnjihia `"vue-paginate": "^3.5.1",`

**Comment by TahaSh** [comment] 2018-03-28 19:39
This issue will be fixed today.

**Comment by TahaSh** [comment] 2018-03-29 14:40
@khaledalam the issue is fixed. Just update to version 3.6.0.

**Closed by TahaSh** 2018-03-29 14:40 UTC
