### ISSUE TITLE
Plugin does not work 

### ISSUE THREAD

**Issue by charlesnjihia** [TahaSh/vue-paginate#80] opened 2018-03-28 11:41 UTC
I followed the documentation to add the plugin on my data set ...it however does not work for me.Anyone that have successfully configured the plugin please assist

**Comment by TahaSh** [comment] 2018-03-28 11:56
@charlesnjihia Do you have any examples?

**Comment by charlesnjihia** [comment] 2018-03-28 12:54
I used the example that you have given after my data never worked i.e.
export default {
  data () {
    return {
      pending: false,
      isScrollAllowed: true,
      moreAfter: true,
      counter: 0,
      langs: ['JavaScript', 'PHP', 'HTML', 'CSS', 'Ruby', 'Python', 'Erlang'],
      paginate: ['languages']
    }
  },


then on the template: 

<div class="tip-container flex wrap group content-start">
         <paginate
          name="languages"
          :list="langs"
          :per="2"
         >
          <li v-for="lang in paginated('languages')">
            {{ lang }}
          </li>
         </paginate>
         <paginate-links for="languages"></paginate-links>        
        </div>



It gives blank with no listed items

**Comment by charlesnjihia** [comment] 2018-03-28 12:56
<div class="tip-container flex wrap group content-start">
         <paginate
          name="languages"
          :list="langs"
          :per="2"
         >
          <li v-for="lang in paginated('languages')">
            {{ lang }}
          </li>
         </paginate>
         <paginate-links for="languages"></paginate-links>        
        </div>



It gives blank with no listed items

**Comment by TahaSh** [comment] 2018-03-28 13:05
What about your html code? Did you add this:
``` html
<paginate
  name="languages"
  :list="langs"
  :per="2"
>
  <li v-for="lang in paginated('languages')">
    {{ lang }}
  </li>
</paginate>
<paginate-links for="languages"></paginate-links>
```

Also, did you check if you installed the plugin successfully?
``` js
import VuePaginate from 'vue-paginate'
Vue.use(VuePaginate)
```

Lastly, do you see any errors in your browser console?

**Comment by charlesnjihia** [comment] 2018-03-28 13:10
I have actually updated my comment to reflect all code.The console givea an error :-1: 
```
Cannot read property 'languages' of undefined
```
I have copied your code to the dot

**Comment by TahaSh** [comment] 2018-03-28 13:27
Please try to `console.log(this.paginate)` in `mounted()` and show me what you get.

**Comment by charlesnjihia** [comment] 2018-03-28 13:38
See the below screenshot for the result of console.log()

![pag](https://user-images.githubusercontent.com/4628217/38032477-6d7f2364-32a6-11e8-9fd2-ab5b911a4588.PNG)

**Comment by TahaSh** [comment] 2018-03-28 16:40
@charlesnjihia Turned out the issue is related to using the plugin inside slots. This issue should be fixed soon in the next release.

**Comment by charlesnjihia** [comment] 2018-03-28 16:55
Anything I could do on the code or the downloaded library to make it work? I woud appreciate

**Comment by charlesnjihia** [comment] 2018-03-28 19:33
@TahaSh  would you heal me understand what you meant by  **using plugin in slots** ?

**Comment by TahaSh** [comment] 2018-03-28 22:46
@charlesnjihia I mean that you're using `<paginate>` and `<paginate-links>` in a slot of a component. For example, pages in quasar framework are wrapped within `<q-page>`. This issue will be fixed within the next 24 hours.

**Comment by charlesnjihia** [comment] 2018-03-28 22:49
thanks @TahaSh

**Comment by TahaSh** [comment] 2018-03-29 15:08
Using the plugin inside slot content is now supported in version 3.6.0. Here's how it works.

In version 3.6.0, we have a new prop in both components (`paginate` and `paginate-links`) called `container`. With this prop, we tell the plugin which component is using our plugin's components and where to find the state of the current pagination.

Although both components have the same prop name (container), they take different values.

For `<paginate>` we pass a reference to the component that contains pagination data (i.e. the one that contains `paginate: ['languages']` in `data()`). This value usually contains `this` value.

`<paginate-links>`, on the other hand, takes an object with two values: `state` and `el`. `state` should contain the state object of the current pagination which we can find inside `paginate` object (e.g. `paginate.languages`). But for `el` we should pass a reference to the component that has the slot content (e.g. `q-page` if you're using `quasar`).

I know this might seem a little bit confusing. Here's some example to make it clearer:

``` html
<template>
  <q-page
    ref="page"
    class="flex flex-center"
  >
    <paginate
      name="languages"
      :container="this"
      :list="langs"
      :per="2"
    >
      <li v-for="lang in paginated('languages')">
        {{ lang }}
      </li>
    </paginate>
    <paginate-links
      for="languages"
      :container="{
        state: paginate.languages,
        el: $refs.page
      }"
    ></paginate-links>
  </q-page>
</template>

<script>
export default {
  name: 'PageIndex',
  data () {
    return {
      langs: ['JavaScript', 'PHP', 'HTML', 'CSS', 'Ruby', 'Python', 'Erlang'],
      paginate: ['languages']
    }
  }
}
</script>
```
So everything is the same as the original example except we're using the new `container` prop. I hope this helps. Don't hesitate to ask any questions you have.

**Closed** 2018-03-30 03:42 UTC
